[shell]
program = "/opt/homebrew/bin/fish"
args = ['--login']

[env]
TERM = "xterm-256color"

[cursor]
style = "Block"

[window]
decorations = "Buttonless"
padding = { x = 10, y = 5 }
dynamic_padding = true

[scrolling]
history = 500

[font]
size = 12.0
normal = { family = "Fira Code", style = "Retina" }
bold = { family = "Fira Code", style = "SemiBold" }

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true
