[shell]
program = "/opt/homebrew/bin/fish"
args = ['--login']

[env]
TERM = "xterm-256color"

[cursor]
style = "Block"

[window]
decorations = "Buttonless"
padding = { x = 10, y = 5 }
dynamic_padding = true

[scrolling]
history = 500

[font]
size = 13.0
normal = { family = "Berkeley Mono" }
bold = { family = "Berkeley Mono", style = "Bold" }
italic = { family = "Berkeley Mono", style = "Italic" }
builtin_box_drawing = true

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleFullscreen" },
]
