approval_policy = "never"
cli_auth_credentials_store = "file"
file_opener = "cursor"
mcp_oauth_credentials_store = "file"
model = "gpt-5.5"
model_auto_compact_token_limit = 270000
model_context_window = 1000000
model_reasoning_effort = "high"
personality = "friendly"
sandbox_mode = "danger-full-access"
service_tier = "fast"
suppress_unstable_features_warning = true
web_search = "live"


notify = ["/Users/kade.killary/.codex/plugins/cache/openai-bundled/computer-use/1.0.755/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[analytics]
enabled = false

[features]
default_mode_request_user_input = true
multi_agent = true
responses_websockets_v2 = true
shell_snapshot = true
unified_exec = true
voice_transcription = true
memories = true

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"
enabled = true

[mcp_servers.ref]
url = "https://api.ref.tools/mcp?apiKey=ref-1f02a8227a14b6bfa1b7"

[mcp_servers.datadog]
url = "https://mcp.datadoghq.com/api/unstable/mcp-server/mcp"

[projects."/Users/kade.killary"]
trust_level = "trusted"

[projects."/Users/kade.killary/dev"]
trust_level = "trusted"

[projects."/Users/kade.killary/dev/simplepractice"]
trust_level = "trusted"

[projects."/Users/kade.killary/dev/ai-sdk"]
trust_level = "trusted"

[projects."/Users/kade.killary/dev/amadeus"]
trust_level = "trusted"

[projects."/Users/kade.killary/dev/langfuse-rb"]
trust_level = "trusted"

[projects."/Users/kade.killary/dippin-dots"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/hoth"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/hoth/work"]
trust_level = "trusted"

[projects."/Users/kade.killary/Desktop/poc-session-copilot-v2"]
trust_level = "trusted"

[projects."/Users/kade.killary/Desktop/poc-session-sidekick"]
trust_level = "trusted"

[projects."/Users/kade.killary/dev/docker-dev"]
trust_level = "trusted"

[projects."/Users/kade.killary/dev/simplepractice-video"]
trust_level = "trusted"

[projects."/Users/kade.killary/Desktop/synthetic-data"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/Codex/2026-04-20-is-fix-http-honor-per-host"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/Codex/2026-04-20-can-you-create-a-linear-issue"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/Codex/2026-04-20-can-you-create-a-linear-issue-2"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/Codex/2026-04-20-what-woudl-be-other-good-automations"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/Codex/2026-04-20-explain-how-this-works-in-rails"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/Codex/2026-04-20-can-you-list-my-created-notion"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/Codex/2026-04-21-what-is-a-codec"]
trust_level = "trusted"

[projects."/Users/kade.killary/Documents/Codex/2026-04-22-move-all-of-my-cycle-24"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[projects."/Users/kade.killary/dev/therapyfinder"]
trust_level = "trusted"

[projects."/Users/kade.killary/Desktop/pokemon-champions"]
trust_level = "trusted"

[projects."/Users/kade.killary/dev/rspec-impact"]
trust_level = "trusted"

[projects."/Users/kade.killary/Desktop/poc-note-format-schema-gen"]
trust_level = "trusted"

[shell_environment_policy]
inherit = "all"

[shell_environment_policy.set]
CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR = "true"
CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY = "1"
CLAUDE_CODE_DISABLE_TERMINAL_TITLE = "1"
CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION = "false"
CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "1"
CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL = "true"
DISABLE_BUG_COMMAND = "1"
DISABLE_COST_WARNINGS = "1"
DISABLE_ERROR_REPORTING = "1"
DISABLE_NON_ESSENTIAL_MODEL_CALLS = "1"
DISABLE_TELEMETRY = "1"
ENABLE_TOOL_SEARCH = "true"
USE_BUILTIN_RIPGREP = "0"

[tui]
status_line = [
    "model-with-reasoning",
    "context-remaining",
    "git-branch",
    "context-window-size",
]
theme = "monokai-extended-bright"

[tui.model_availability_nux]
"gpt-5.5" = 4

[[skills.config]]
path = "/Users/kade.killary/Desktop/symphony/.codex/skills/pull/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/Desktop/symphony/.codex/skills/push/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/Desktop/symphony/.codex/skills/debug/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/Desktop/symphony/.codex/skills/commit/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/Desktop/codex/.codex/skills/babysit-pr/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/Desktop/symphony/.codex/skills/land/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/.codex/skills/.system/skill-installer/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/.codex/skills/.system/skill-creator/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/.codex/skills/.system/plugin-creator/SKILL.md"
enabled = false

[[skills.config]]
name = "notion:notion-knowledge-capture"
enabled = false

[[skills.config]]
name = "notion:notion-meeting-intelligence"
enabled = false

[[skills.config]]
name = "notion:notion-research-documentation"
enabled = false

[[skills.config]]
name = "notion:notion-spec-to-implementation"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/dippin-dots/codex/.codex/skills/linear-update/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kade.killary/.codex/skills/.system/openai-docs/SKILL.md"
enabled = false

[plugins."github@openai-curated"]
enabled = true

[plugins."plugin-eval@openai-curated"]
enabled = false

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = false

[plugins."browser-use@openai-bundled"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-04-24T20:18:34Z"
source_type = "local"
source = "/Users/kade.killary/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-04-23T18:25:29Z"
source_type = "local"
source = "/Users/kade.killary/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[apps.asdk_app_69c18c28f1188191bf5b8445c4ab0a2e]
enabled = false
