-- local tsc = require('telescope')

-- opts = tsc.setup{
    -- defaults = {
        -- prompt_prefix = '❯ ',
        -- selection_caret = '▍ ',
        -- entry_prefix = ' ',
        -- initial_mode = "insert",
        -- selection_strategy = "reset",
        -- sorting_strategy = "ascending",
        -- layout_strategy = "horizontal",
        -- layout_config = {
        -- horizontal = {
            -- prompt_position = "top",
            -- preview_width = 0.55,
            -- results_width = 0.8,
        -- },
        -- vertical = {
            -- mirror = false,
        -- },
        -- width = 0.87,
        -- height = 0.80,
        -- preview_cutoff = 120,
        -- },
        -- -- file_sorter = require("telescope.sorters").get_fuzzy_file,
        -- -- file_ignore_patterns = { '.git/', '.cache', '__pycache__', 'target' }
        -- -- generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
        -- path_display = { "truncate" },
        -- winblend = 0,
        -- border = {},
        -- -- borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
        -- borderchars = { " ", " ", " ", " ", " ", " ", " ", " " },
        -- set_env = { ["COLORTERM"] = "truecolor" }, -- default = nil,
        -- mappings = {
            -- n = { ["q"] = require("telescope.actions").close },
            -- i = {
                -- ["<C-j>"] = require('telescope.actions').move_selection_next,
                -- ["<C-k>"] = require('telescope.actions').move_selection_previous,
            -- }
        -- }
    -- },
    -- extensions_list = { "themes", "terms" }
-- }
